project: Test_run
sequence_files:
  file1:
    name: /scratch/g/chlin/Yu/zUMIs/tests/data/sample/read_1_sample.fq.gz
    base_definition:
      - cDNA(25-100)
      - UMI(12-21)
    find_pattern: ATTGCGCAATG;2
  file2:
    name: /scratch/g/chlin/Yu/zUMIs/tests/data/sample/read_2_sample.fq.gz
    base_definition:
      - cDNA(1-100)
      - BC(101-120)
reference:
  STAR_index: /scratch/g/chlin/library/hg38/star/
  GTF_file: /scratch/g/chlin/library/hg38/genes/genes.gtf
  additional_STAR_params: '--clip3pAdapterSeq CTGTCTCTTATACACATCT'
  additional_files:
out_dir: /scratch/g/chlin/Yu/zUMIs/tests/output
num_threads: 20
mem_limit: 50
filter_cutoffs:
  BC_filter:
    num_bases: 4
    phred: 20
  UMI_filter:
    num_bases: 3
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: null
  automatic: yes
  BarcodeBinning: 1
  demultiplex: no
  nReadsperCell: 100
  discardReads: yes
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 1
  Ham_Dist: 1
  velocyto: no
  primaryHit: yes
  twoPass: no
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript
zUMIs_directory: .
